### ISSUE TITLE
Error setting up entry IRTrans for irtrans

### ISSUE THREAD

**Issue by chelefteo** [schwarzenbergf/irtrans#168]
## Configuration

```yaml

Add your logs here.

2024-10-03 10:11:22.834 DEBUG (MainThread) [custom_components.irtrans] ->async_setup_entry:Config Entry data (async_setup_entry) {'host': '192.168.1.10', 'port': '21000'} :
2024-10-03 10:11:22.835 DEBUG (MainThread) [custom_components.irtrans] IRTransDataUpdateCoordinator
2024-10-03 10:11:22.835 DEBUG (MainThread) [custom_components.irtrans] hass cfg entry(IRTransDataUpdateCoordinator): 192.168.1.10:21000
2024-10-03 10:11:22.835 DEBUG (MainThread) [custom_components.irtrans] Get Version msg sent (_async_update_data)
2024-10-03 10:11:22.885 DEBUG (MainThread) [custom_components.irtrans] Data received **00034 VERSION E6.08.42 L1.11.06:
2024-10-03 10:11:22.885 DEBUG (MainThread) [custom_components.irtrans] Version/Firmware ['**00034', 'VERSION', 'E6.08.42 L1.11.06']/E6.08.42 L1.11.06:
2024-10-03 10:11:23.836 DEBUG (MainThread) [custom_components.irtrans] Finished fetching irtrans data in 1.001 seconds (success: True)
2024-10-03 10:11:23.839 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry IRTrans for irtrans
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/irtrans/__init__.py", line 94, in async_setup_entry
    entities[0],
    ~~~~~~~~^^^
IndexError: list index out of range
2024-10-03 10:11:23.845 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration, irtrans with title: IRTrans and entry_id: 01J94TC7Q3XFT2VS0VN430FDXK, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead. Please report this issue.
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2195, in async_forward_entry_setup
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 155, in report
    _LOGGER.warning(msg, stack_info=True)
2024-10-03 10:11:23.845 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2207, in async_forward_entry_setup
    raise OperationNotAllowed(
homeassistant.config_entries.OperationNotAllowed: The config entry 'IRTrans' (irtrans) with entry_id '01J94TC7Q3XFT2VS0VN430FDXK' cannot forward setup for sensor because it is in state ConfigEntryState.SETUP_ERROR, but needs to be in the ConfigEntryState.LOADED state

## Describe the bug
Error setting up entry IRTrans for irtrans


## Debug log

<!-- To enable debug logs check this https://www.home-assistant.io/components/logger/ -->

```text

Add your logs here.

```

**Comment by chelefteo** [comment]
Error setting up entry IRTrans for irtrans with state ConfigEntryState.SETUP_ERROR

**Comment by schwarzenbergf** [comment]
I released a new version. It does not directly address your problem, but please check anyway and send me the log file.

**Comment by schwarzenbergf** [comment]
From other comments I know that this problem seems to be solved with the new version.
I close this issue. Reopen if you still experience this problem.

**Comment by chelefteo** [comment]
Yes great work, seems to be solved with this version. Thank you very much.
